site_name: WinfoWiki

theme:
    name: material
    language: de
    features:
        - navigation.instant

extra_javascript:
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
    - smarty
    - toc:
        permalink: "#"
    - sane_lists
    - pymdownx.arithmatex:
        generic: true
    - tables
    - attr_list
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - def_list

plugins:
    - mermaid2
    - search:
        lang:
          - de
          - en

repo_url: https://github.com/heshsum/winfowiki
